version: '3.6'

services:
  lora-node:
    image: wero1414/lora-node-x8:latest-arm64
    container_name: 'lora-node'
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - '/var/run/secrets:/app/config/'
      - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
    extra_hosts:
      - 'm4-proxy:host-gateway'
    devices:
      - '/dev/ttymxc3'
      - '/dev/gpiochip5'
    tty: true
    user: "0"