version: '3.6'

services:
  python-hello-world:
    image: wero1414/python-hello-world:latest-arm64
    restart: always
    tty: true
    read_only: true
    user: "63"
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    ports:
    - "80:80"
